# SPDX-FileCopyrightText: 2023 - 2025 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure MRS paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ mrs_uid }}"
    group: "{{ mrs_gid }}"
  with_items:
    - "{{ mrs_base_path }}"
    - "{{ mrs_data_dir_path }}"

- name: Ensure MRS support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ mrs_base_path }}/{{ item }}"
    owner: "{{ mrs_uid }}"
    group: "{{ mrs_gid }}"
    mode: 0640
  with_items:
    - config.yml
    - labels

- name: Ensure MRS container image is pulled
  community.docker.docker_image:
    name: "{{ mrs_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ mrs_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else mrs_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure MRS container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ mrs_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure MRS systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/{{ item.src }}"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ item.dst }}"
    mode: 0640
  with_items:
    - src: mrs.service.j2
      dst: "{{ mrs_identifier }}.service"
