# SPDX-FileCopyrightText: 2023 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required MRS settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - mrs_hostname
    - mrs_uid
    - mrs_gid

- name: Fail if required MRS + Traefik integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `mrs_container_labels_traefik_enabled`
  when: "mrs_container_labels_traefik_enabled | bool and vars[item] == ''"
  with_items:
    - mrs_container_labels_traefik_docker_network
